@startuml

class Batalla
class Ejercito {
    -numeroDeTropas: int
    +reducirTropas()
    +aumentarTropas()
    +obtenerNumeroTotalDeTropas(): int
    +atacar(cantidadDeTropas, otroEjercito)
}

Batalla .. Ejercito

@enduml