@startuml

class Mapa {
    -paises: HashMap
    {static}+Mapa(ruta: String)
    +inicializar(jugadores: Jugadores[])
    +obtenerPais(nombre: String)
    +size()
}

class CargadorDePaises {
    {static}+cargarPaisesConRuta(ruta: String)
    -cargarCsv(ruta: String)
}

Mapa --> CargadorDePaises

@enduml